# Generated by Django 5.2 on 2025-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_visitor_reason_alter_visitor_visitor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='otp_code',
            new_name='code',
        ),
    ]
