# Generated by Django 5.2 on 2025-04-20 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_rename_otp_code_emailotp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
