# Generated by Django 5.2 on 2025-05-22 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=50)),
                ('laptop_tag_no', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
